### ISSUE TITLE
Frontend: Suggestions from MG

### ISSUE THREAD

**Issue by ThomasPause** [hitontology/instancegenerator#12]
Talking to MG produced the following todos for the frontend dev: 
- [x] use classes as headlines instead of relations, see #2
- [x] vertical view for fields
- [x] choice of attributes and field "other" for new attribute

Just to get an idea, here are the first fields as mockup:
![mockup](https://user-images.githubusercontent.com/27236726/74247588-95f0d980-4ce6-11ea-8369-bc3e836f7cd6.png)

--- 
For more detail see the handwritten Mockup

**Comment by KonradHoeffner** [comment]
@maghalandari: Can you give an example or mockup of the saved values? Should it show other instances that were created earlier or should it instead show all selected values?

**Comment by KonradHoeffner** [comment]
Compromise: The name of the relation is the label of the field and the name of the class is the placeholder text.

**Comment by KonradHoeffner** [comment]
Field "other" was decided against in #15.
