### ISSUE TITLE
Interface 

### ISSUE THREAD

**Issue by maghalandari** [hitontology/instancegenerator#25]
Dear Konrad,
This feature of interface should change.
Interoperability have 3 subscribe Semantic interoperability, Syntactic interoperability, Technical interoperability. And these subscribe have instance like HL7, DICOM
Please create box for them for insert data.
- [x] Organizational unit citation
- [x] Organizational unit classified
- [x] User group citation
- [x] User group classified
- [x] Enterprise function citation
- [x] Enterprise function classified
- [x] Feature citation
- [x] Feature classified

- [x] And all of citation group need to one box for citation and one for classified.
- [ ] Please create feature classified box with number (xyz) and name of catalogue.
- [x] For connection we need to know this feature is from which catalogue.
- [x] Please manage feature catalogue part. For example not mixed all catalogue in one box.one selection box with name of catalogue and see feature of catalogue.

Please change this Label of box
- [x] Uses database to database
- [x] Offers feature to feature 
- [x] Suitable for organisational unit to organisation unit
- [x] Runs on OS to operating system
- [ ] Software product component to software product
- [x] Implements we don’t have this class…..
- [x] Supports language to language
- [x] Support client to client
- [x] Support enterprise function to enterprise function citation

**Comment by KonradHoeffner** [comment]
@maghalandari I implemented most of them but I am not sure if "software product component" should  be renamed to "software product", I think this could confuse users because they won't know what the relationship is.

**Comment by KonradHoeffner** [comment]
Everything implemented except "software product component" (see above) and the display of the member number of classified entries, which causes a timeout due to too many optionals, see https://stackoverflow.com/questions/6280670/optimization-of-sparql-query-estimated-execution-time-exceeds-the-limit-of-15.

If this is should still be continued, please open a separate issue for that.
