### ISSUE TITLE
Fix CORS

### ISSUE THREAD

**Issue by KonradHoeffner** [hitontology/instancegenerator#26]

**Comment by ThomasPause** [comment]
CORS error seems to occur because of an invalid CORS Header. Still investigating..
a test.html script can be run to test if queries on Hito endpoint and dbpedia are successful or not

**Comment by KonradHoeffner** [comment]
The test script is available at https://hitontology.github.io/instancegenerator/cors.html.

**Comment by KonradHoeffner** [comment]
`https://hitontology.github.io/instancegenerator/` tells me the following on Firefox developer edition 74.0b9:

```Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at https://hitontology.eu/sparql?query=SELECT%20%3Furi%20STR(SA…son&default-graph-uri=http%3A%2F%2Fhitontology.eu%2Fontology. (Reason: CORS header ‘Access-Control-Allow-Origin’ does not match ‘null’).

Error executing SPARQL query sparql.js:23:13
Error: NetworkError when attempting to fetch resource.
SELECT ?uri STR(SAMPLE(?label)) as ?label ?type ?range
    {
      ?uri rdfs:domain <http://hitontology.eu/ontology/SoftwareProduct>;
      rdfs:range ?range;
      rdf:type ?type.
      FILTER(?type=owl:DatatypeProperty OR ?type=owl:ObjectProperty)
      OPTIONAL {?uri rdfs:label ?label.}
    }
URL, https://hitontology.eu/sparql?query=SELECT%20%3Furi%20STR(SA…son&default-graph-uri=http%3A%2F%2Fhitontology.eu%2Fontology```

**Comment by KonradHoeffner** [comment]
How to retrace this bug:
1. Access https://hitontology.github.io/instancegenerator/cors.html -> everything should be fine
2. Set up a local webserver with `python -m http.server`
3. Access `http://localhost:8000/cors.html` -> error (sometimes only on DBpedia)

**Comment by KonradHoeffner** [comment]
Here is a good explanation of CORS with fetch: https://stackoverflow.com/questions/43262121/trying-to-use-fetch-and-pass-in-mode-no-cors

**Comment by KonradHoeffner** [comment]
However the problem seems to be switching between browser and file protocol, as the cache is preserving the origin, which is changing.

The only way I found to alleviate this problem is to delete the browser cache when changing the URI. This is unfortunately but not a showstopper as the end user will not face this problem as they always use the same URI.
