### ISSUE TITLE
create new catalogues

### ISSUE THREAD

**Issue by ThomasPause** [hitontology/instancegenerator#31]
According to #10 we need 2 more catalogues:
- [x] organizational unit
- [x] user group

**Comment by ThomasPause** [comment]
FJ said, organizational unit catalogue is not needed right now.

For organizational unit we could use something like [this](http://dbpedia.org/page/Health_professional).
Maybe combined with the possibility to add a new value, that is not provided.

**Comment by KonradHoeffner** [comment]
Included both.
