### ISSUE TITLE
feature catalogue

### ISSUE THREAD

**Issue by maghalandari** [hitontology/instancegenerator#32]
Dear Konrad,
I have small discussion with Franziska,
In interface we should have xyz number and cataloge name with feature in box.we can not manage if we dont have number and name.

**Comment by KonradHoeffner** [comment]
As we use the database frontend https://github.com/hitontology/database-frontend I don't think this is needed for know so I will close this. However we could do it in the database frontend, in case the number exists for a classified entry. Right now this is partially done by including the number in the label.
