### ISSUE TITLE
Search for catalogues does not work for small amount of chars

### ISSUE THREAD

**Issue by ThomasPause** [hitontology/instancegenerator#33]
you need to type at least 2 different chars to start the search..
Bug or Feature? ;)

**Comment by KonradHoeffner** [comment]
This is strange because we define `minCharacters: 0` in `catalogueSelect.js`, I count this as a bug.

**Comment by KonradHoeffner** [comment]
This seems to be a problem of matching too much.
Changing `searchFields: ["category", "title", "description"],`  to `searchFields: ["title"],` reduces the problem but we still see `https://hitontology.eu/ontology/CivilRegistrationAndVitalStatistics` when searching for "env".
