### ISSUE TITLE
rework catalogue workflow

### ISSUE THREAD

**Issue by KonradHoeffner** [hitontology/instancegenerator#47]
The user should first input the citation on the left side and then select a catalog entry on the right side. It must be possible, however, not to specify a citation, but to select only the catalogue entry. There must be a possibility to say that you do not want to enter anything in Citation. "Button to say I'm going to the right"

**Comment by ThomasPause** [comment]
this function is urgently needed for the examples

**Comment by KonradHoeffner** [comment]
This was implemented on the ontology side by adding properties that connect hito:SoftwareProduct directly with the classified catalogue entries. So for this use case don't use the catalogue interface at all but just the normal "Attributes" tab.
