### ISSUE TITLE
saving more than one ApplicationSystems is impossible

### ISSUE THREAD

**Issue by ThomasPause** [hitontology/instancegenerator#55]

**Comment by KonradHoeffner** [comment]
It works using the attributes interface it works.
Using the catalogue interface it also works with two citations to two different classified entries.
But what doesn't work is having two citations for the same classified entries, that is the use case, right?

**Comment by KonradHoeffner** [comment]
Implemented in https://github.com/hitontology/instancegenerator/commit/827658402bce8228b84f80ff6ed3cf2eb5da9113.
