### ISSUE TITLE
"Your request URL is too long." when submitting to GitHub

### ISSUE THREAD

**Issue by KonradHoeffner** [hitontology/instancegenerator#60]
Products with many attributes go over the URL max length limit when submitting the ticket to GitHub.
URIs over a certain length could have a fallback method where the user copies the triples manually.
However that is even more cumbersome than the method employed right now, can we use POST for GitHub?

See https://developer.github.com/v3/issues/#create-an-issue.

The URL would be https://api.github.com/repos/hitontology/instancegenerator/issues.

The problem is, that POST requests seem to require an access token to authenticate as a user, it does not seem possible to create an issue with the active user like with GET. 

See the StackOverflow post at https://stackoverflow.com/questions/62219284/how-to-post-an-issue-stub-on-github-using-the-github-api-using-the-logged-in-use.

**Comment by ThomasPause** [comment]
also got the same error while trying to insert GNUHealth

**Comment by ThomasPause** [comment]
maybe we should use the users clipboard and then add it into a github issue

**Comment by KonradHoeffner** [comment]
This will be superseded by the relational database workflow.
